language: "node_js"
node_js: # jest and eslint no longer support v4
  - "6"
  - "8"
os:
  - "linux"
  - "osx"
branches:
  only:
  - "master"
  - "develop"
cache:
  directories:
    - "node_modules"
script:
  - "npm test"
  - "npm run lint"
