# https://help.github.com/ja/articles/workflow-syntax-for-github-actions

on:
  push:
    branches:
    - master
    - develop
  pull_request:
name: Build check
jobs:
  verify:
    name: Build on ${{ matrix.platform }} / Node.js v${{ matrix.nodejs }}
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform:
        - "windows-latest"
        - "macOS-latest"
        - "ubuntu-latest"
        nodejs:
        - 4
        - 6
        - 8
        - 10
        - 12
    steps:
    - name: Turn off auto-crlf
      run: git config --global core.autocrlf false
    - name: Checkout source codes
      uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}
    - name: Install dependencies
      run: npm i
    - name: Build
      run: npm run build
