on:
  release:
    types:
    - published
name: publish
jobs:
  publish:
    name: publish to npmjs.com
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v1
    - name: Install dependencies
      run: npm ci
    - name: Publish package
      uses: actions/npm@v2
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      with:
        args: publish
