on:
  push:
    branches:
    - master
    - develop
  pull_request:
name: Syntax check
jobs:
  syntax:
    name: Check on ${{ matrix.platform }} / Node.js v${{ matrix.nodejs }}
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform:
        - "Windows-latest"
        - "macOS-latest"
        - "Ubuntu-latest"
        nodejs:
        - "4.0.0"
        - "6.0.0"
    steps:
    - name: Turn off auto-crlf
      run: git config --global core.autocrlf false
    - name: Checkout source codes
      uses: actions/checkout@v1
    - name: Install Node.js v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install npm packages
      run: npm i -g node-gyp
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Reinstall Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}
    - name: Check syntax
      run: node ./dist/index.js
