# https://help.github.com/ja/articles/workflow-syntax-for-github-actions

on:
  push:
    branches:
    - master
    - develop
  pull_request:
name: Linux
jobs:
  verify:
    name: Verify on Node.js v${{ matrix.nodejs }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs:
        - "8"
        - "10"
        - "12"
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}
    - name: Clean install dependencies
      run: npm ci
    - name: Verify
      run: npm run verify
    - name: Report code coverage
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
