# https://help.github.com/ja/articles/workflow-syntax-for-github-actions

on:
  push:
    branches:
    - master
    - develop
  pull_request:
name: macOS
jobs:
  verify:
    name: Verify on Node.js v${{ matrix.nodejs }}
    runs-on: macOS-latest
    strategy:
      matrix:
        nodejs:
        - 6
        - 8
        - 10
        - 12
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}
    - name: Update npm
      run: npm install -g npm
    - name: Clean install dependencies
      run: npm ci
    - name: Verify
      run: npm run verify
