# https://help.github.com/ja/articles/workflow-syntax-for-github-actions

on:
  push:
    branches:
    - master
    - develop
  pull_request:
name: Windows
jobs:
  verify:
    name: Verify source codes
    runs-on: windows-latest
    strategy:
      matrix:
        nodejs:
        - '6'
        - '8'
        - '10'
        - '12'
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}
    - name: Clean install dependencies and verify
      run: |
        npm ci
        npm run verify
